version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nars-painel
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    network_mode: host   # usar host para acessar MySQL e Redis locais via 127.0.0.1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: nars-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
